[features]
seeds = false
skip-lint = false
[programs.localnet]
suscriber = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
publisher = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/alejo-mac-thinkdev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
